services:
  - type: web
    name: zoobi-chat-backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:./data/chat_db
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.H2Dialect
      - key: SPRING_H2_CONSOLE_ENABLED
        value: true
