services:
  - type: web
    name: boxbi-backend
    env: docker
    dockerfilePath: server-spring/Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: boxbi-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: boxbi-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: boxbi-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: boxbi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: boxbi-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
    plan: free

databases:
  - name: boxbi-db
    databaseName: boxbi
    user: boxbi_user
    plan: free
